Pranay
utpalbora/compilers.cse.iith.ac.in pull request #116
Opened 2024-05-17 01:58 UTC by mr-pranay

Modifications regarding publications

2024-05-17 13:51 UTC, svkeerthy requested changes

2024-05-17 13:51 UTC, svkeerthy commented on _layouts/bibtemplate.html
> +
Please cleanup the empty lines and commented portion of the code.

2024-05-17 13:52 UTC, svkeerthy commented
Please write the objective of the PR precisely in the PR title and description.

2024-05-18 06:53 UTC, mr-pranay commented
- Added Jekyll Scholar gem 
- Created a new folder (_bibliography) to store BibTeX files containing publication information
-  Added a BibTeX template formatting file for rendering publications according to our design requirements

2024-05-18 07:03 UTC, svkeerthy approved these changes

2024-05-18 07:03 UTC, merged